# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: flxsrbr
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal GitHub Page of flxsrbr
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: flxsrbr
github_username:  flxsrbr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
